Imports Microsoft.Office.Interop
Imports Microsoft.Office.Interop.PowerPoint
Imports Microsoft.Office.Core
Imports System.Drawing

Module Module1
    Dim BackboneHeight As Single = 18
    Dim FeatureExtension As Single = 4
    Dim FeatureHeight As Single = BackboneHeight + 2 * FeatureExtension
    Dim BackboneTop As Single = 10
    Dim FeatureTop As Single = 10 - FeatureExtension
    Dim BackboneLeft As Single = 65
    Dim BackboneWidth As Single = 625
    Dim MaxProteinLength As Single = 200

    Sub Main()
        Dim ppApp As Application = New Application
        Dim ppPres As Presentation


        ppApp = New PowerPoint.Application
        ppApp.Visible = MsoTriState.msoTrue
        ppPres = ppApp.Presentations.Add
        Dim custLayout As CustomLayout = ppPres.SlideMaster.CustomLayouts(7)

        'CustomLayouts indexes for the Normal template's SlideMaster are as follows:
        ' 1 = Title Slide
        ' 2 = Title and Content
        ' 3 = Section Header
        ' 4 = Two Content
        ' 5 = Comparison
        ' 6 = Title Only
        ' 7 = Blank
        ' 8 = Content with Caption
        ' 9 = Picture with Caption
        ' 10 = Title and Vertical Caption
        ' 11 = Vertical Title and Text

        ppPres.Slides.AddSlide(1, custLayout) 'PowerPoint objects are generally 1-indexed
        Dim ppSlide As Slide = ppPres.Slides(1)

        ''Ntg1
        'NewProtein(0, "Ntg1", 399, ppSlide)
        'AddMTS(0, 0, 1, 17, 399, ppSlide)
        'AddNLS(0, 0, 14, 17, 399, ppSlide)
        'AddNLS(0, 0, 31, 36, 399, ppSlide)
        'AddNES(0, 0, 173, 190, 399, ppSlide)
        'AddNES(0, 0, 389, 395, 399, ppSlide)
        'AddMotif1(0, 0, 225, 254, 399, ppSlide)
        'AddSUMOSite(0, 0, 20, 399, ppSlide)
        'AddSUMOSite(0, 0, 38, 399, ppSlide)
        'AddSUMOSite(0, 0, 364, 399, ppSlide)
        'AddSUMOSite(0, 0, 388, 399, ppSlide)
        'AddSUMOSite(0, 0, 396, 399, ppSlide)
        'AddUbSite(0, 0, 20, 380, ppSlide)
        'AddUbSite(0, 0, 33, 380, ppSlide)
        'AddUbSite(0, 0, 296, 380, ppSlide)
        'AddUbSite(0, 0, 380, 380, ppSlide)
        'AddUbSite(0, 0, 388, 380, ppSlide)
        'AddUbSite(0, 0, 396, 380, ppSlide)
        'AddAceSite(0, 0, 33, 359, ppSlide)
        'AddAceSite(0, 0, 91, 359, ppSlide)
        'AddAceSite(0, 0, 95, 359, ppSlide)
        'AddAceSite(0, 0, 109, 359, ppSlide)
        'AddAceSite(0, 0, 129, 359, ppSlide)
        'AddAceSite(0, 0, 210, 359, ppSlide)
        'AddAceSite(0, 0, 315, 359, ppSlide)
        'AddAceSite(0, 0, 364, 359, ppSlide)
        'AddPhosSite(0, 0, 9, 399, ppSlide)
        'AddPhosSite(0, 0, 138, 399, ppSlide)
        'AddPhosSite(0, 0, 224, 399, ppSlide)
        'AddPhosSite(0, 0, 225, 399, ppSlide)
        'AddPhosSite(0, 0, 334, 399, ppSlide)
        'AddPhosSite(0, 0, 23, 399, ppSlide)
        'AddPhosSite(0, 0, 77, 399, ppSlide)
        'AddPhosSite(0, 0, 86, 399, ppSlide)
        'AddPhosSite(0, 0, 282, 399, ppSlide)

        ''Ntg2
        'NewProtein(1, "Ntg2", 380, ppSlide)
        'AddMotif1(1, 0, 230, 259, 380, ppSlide)
        'AddNLS(1, 0, 8, 12, 380, ppSlide)
        'AddNLS(1, 0, 376, 380, 380, ppSlide)
        'AddNES(1, 0, 181, 193, 380, ppSlide)
        'AddSUMOSite(1, 0, 116, 380, ppSlide)
        'AddSUMOSite(1, 0, 194, 380, ppSlide)
        'AddUbSite(1, 0, 9, 380, ppSlide)
        'AddUbSite(1, 0, 11, 380, ppSlide)
        'AddUbSite(1, 0, 86, 380, ppSlide)
        'AddAceSite(1, 0, 11, 380, ppSlide)
        'AddAceSite(1, 0, 25, 380, ppSlide)
        'AddAceSite(1, 0, 29, 380, ppSlide)
        'AddAceSite(1, 0, 38, 380, ppSlide)
        'AddAceSite(1, 0, 96, 380, ppSlide)
        'AddAceSite(1, 0, 341, 380, ppSlide)
        'AddAceSite(1, 0, 347, 380, ppSlide)
        'AddPhosSite(1, 0, 5, 380, ppSlide)
        'AddPhosSite(1, 0, 117, 380, ppSlide)

        ''Ung1
        'NewProtein(2, "Ung1", 359, ppSlide)
        'AddMotif1(2, 0, 155, 164, 359, ppSlide)
        'AddMTS(2, 0, 1, 20, 359, ppSlide)
        'AddNLS(2, 0, 5, 21, 359, ppSlide)
        'AddNLS(2, 0, 38, 44, 359, ppSlide)
        'AddNES(2, 0, 91, 102, 359, ppSlide)
        'AddSUMOSite(2, 0, 58, 359, ppSlide)
        'AddSUMOSite(2, 0, 178, 359, ppSlide)
        'AddSUMOSite(2, 0, 195, 359, ppSlide)
        'AddUbSite(2, 0, 31, 359, ppSlide)
        'AddUbSite(2, 0, 32, 359, ppSlide)
        'AddUbSite(2, 0, 58, 359, ppSlide)
        'AddUbSite(2, 0, 66, 359, ppSlide)
        'AddUbSite(2, 0, 72, 359, ppSlide)
        'AddUbSite(2, 0, 80, 359, ppSlide)
        'AddAceSite(2, 0, 40, 359, ppSlide)
        'AddAceSite(2, 0, 43, 359, ppSlide)
        'AddAceSite(2, 0, 58, 359, ppSlide)
        'AddAceSite(2, 0, 62, 359, ppSlide)
        'AddAceSite(2, 0, 80, 359, ppSlide)
        'AddAceSite(2, 0, 85, 359, ppSlide)
        'AddAceSite(2, 0, 140, 359, ppSlide)
        'AddAceSite(2, 0, 260, 359, ppSlide)
        'AddAceSite(2, 0, 289, 359, ppSlide)
        'AddPhosSite(2, 0, 33, 359, ppSlide)
        'AddPhosSite(2, 0, 44, 359, ppSlide)
        'AddPhosSite(2, 0, 302, 359, ppSlide)
        'AddPhosSite(2, 0, 341, 359, ppSlide)
        'AddPhosSite(2, 0, 149, 359, ppSlide)
        'AddPhosSite(2, 0, 181, 359, ppSlide)
        'AddMethSite(2, 0, 85, 359, ppSlide)
        'AddMethSite(2, 0, 308, 359, ppSlide)
        'AddPalmSite(2, 0, 3, 359, ppSlide)

        ''Mag1
        'NewProtein(3, "Mag1", 296, ppSlide)
        'AddMotif1(3, 0, 185, 209, 296, ppSlide)
        'AddNLS(3, 0, 243, 246, 296, ppSlide)
        'AddSUMOSite(3, 0, 4, 296, ppSlide)
        'AddSUMOSite(3, 0, 12, 296, ppSlide)
        'AddSUMOSite(3, 0, 288, 296, ppSlide)
        'AddUbSite(3, 0, 288, 296, ppSlide)
        'AddUbSite(3, 0, 295, 296, ppSlide)
        'AddAceSite(3, 0, 137, 296, ppSlide)
        'AddAceSite(3, 0, 142, 296, ppSlide)
        'AddAceSite(3, 0, 218, 296, ppSlide)
        'AddAceSite(3, 0, 223, 296, ppSlide)
        'AddAceSite(3, 0, 235, 296, ppSlide)
        'AddAceSite(3, 0, 241, 296, ppSlide)
        'AddAceSite(3, 0, 245, 296, ppSlide)
        'AddAceSite(3, 0, 250, 296, ppSlide)
        'AddPhosSite(3, 0, 93, 296, ppSlide)
        'AddPhosSite(3, 0, 97, 296, ppSlide)
        'AddPhosSite(3, 0, 103, 296, ppSlide)
        'AddPhosSite(3, 0, 110, 296, ppSlide)
        'AddPhosSite(3, 0, 221, 296, ppSlide)
        'AddPhosSite(3, 0, 265, 296, ppSlide)

        ''Ogg1
        'NewProtein(4, "Ogg1", 376, ppSlide)
        'AddMotif1(4, 0, 235, 262, 376, ppSlide)
        'AddMTS(4, 0, 1, 38, 376, ppSlide)
        'AddNLS(4, 0, 341, 343, 376, ppSlide)
        'AddNLS(4, 0, 291, 297, 376, ppSlide)
        'AddNES(4, 0, 359, 370, 376, ppSlide)
        'AddSUMOSite(4, 0, 362, 376, ppSlide)
        'AddAceSite(4, 0, 93, 376, ppSlide)
        'AddAceSite(4, 0, 109, 376, ppSlide)
        'AddAceSite(4, 0, 191, 376, ppSlide)
        'AddAceSite(4, 0, 281, 376, ppSlide)
        'AddAceSite(4, 0, 341, 376, ppSlide)
        'AddPhosSite(4, 0, 111, 376, ppSlide)
        'AddPhosSite(4, 0, 334, 376, ppSlide)

        ''Apn1
        'NewProtein(5, "Apn1", 367, ppSlide)
        'AddMotif1(5, 0, 106, 117, 376, ppSlide)
        'AddMotif1(5, 0, 83, 91, 367, ppSlide)
        'AddMotif1(5, 0, 188, 195, 367, ppSlide)
        'AddMotif1(5, 0, 228, 244, 367, ppSlide)
        'AddMTS(5, 0, 1, 51, 367, ppSlide)
        'AddNLS(5, 0, 341, 344, 367, ppSlide)
        'AddNLS(5, 0, 360, 363, 367, ppSlide)
        'AddNLS(5, 0, 322, 338, 367, ppSlide)
        'AddSUMOSite(5, 0, 129, 367, ppSlide)
        'AddUbSite(5, 0, 296, 367, ppSlide)
        'AddUbSite(5, 0, 308, 367, ppSlide)
        'AddAceSite(5, 0, 14, 367, ppSlide)
        'AddAceSite(5, 0, 129, 367, ppSlide)
        'AddAceSite(5, 0, 145, 367, ppSlide)
        'AddAceSite(5, 0, 151, 367, ppSlide)
        'AddAceSite(5, 0, 154, 367, ppSlide)
        'AddAceSite(5, 0, 316, 367, ppSlide)
        'AddAceSite(5, 0, 341, 367, ppSlide)
        'AddPhosSite(5, 0, 6, 367, ppSlide)
        'AddPhosSite(5, 0, 48, 367, ppSlide)
        'AddPhosSite(5, 0, 54, 367, ppSlide)
        'AddPhosSite(5, 0, 101, 367, ppSlide)
        'AddPhosSite(5, 0, 297, 367, ppSlide)
        'AddPhosSite(5, 0, 350, 367, ppSlide)
        'AddPhosSite(5, 0, 275, 367, ppSlide)

        ''Apn2
        'NewProtein(6, "Apn2", 520, ppSlide)
        'AddNLS(6, 0, 452, 458, 520, ppSlide)
        'AddNES(6, 0, 148, 160, 520, ppSlide)
        'AddMotif1(6, 0, 322, 333, 520, ppSlide)
        'AddSUMOSite(6, 0, 61, 520, ppSlide)
        'AddSUMOSite(6, 0, 113, 520, ppSlide)
        'AddSUMOSite(6, 0, 335, 520, ppSlide)
        'AddSUMOSite(6, 0, 379, 520, ppSlide)
        'AddUbSite(6, 0, 12, 520, ppSlide)
        'AddUbSite(6, 0, 441, 520, ppSlide)
        'AddUbSite(6, 0, 446, 520, ppSlide)
        'AddUbSite(6, 0, 472, 520, ppSlide)
        'AddAceSite(6, 0, 61, 520, ppSlide)
        'AddAceSite(6, 0, 125, 520, ppSlide)
        'AddAceSite(6, 0, 201, 520, ppSlide)
        'AddAceSite(6, 0, 385, 520, ppSlide)
        'AddAceSite(6, 0, 410, 520, ppSlide)
        'AddAceSite(6, 0, 415, 520, ppSlide)
        'AddAceSite(6, 0, 441, 520, ppSlide)
        'AddAceSite(6, 0, 463, 520, ppSlide)
        'AddAceSite(6, 0, 496, 520, ppSlide)
        'AddAceSite(6, 0, 501, 520, ppSlide)
        'AddPhosSite(6, 0, 188, 520, ppSlide)
        'AddPhosSite(6, 0, 189, 520, ppSlide)
        'AddPhosSite(6, 0, 232, 520, ppSlide)
        'AddPhosSite(6, 0, 321, 520, ppSlide)
        'AddPhosSite(6, 0, 429, 520, ppSlide)
        'AddPhosSite(6, 0, 432, 520, ppSlide)
        'AddPhosSite(6, 0, 449, 520, ppSlide)
        'AddPhosSite(6, 0, 460, 520, ppSlide)
        'AddPhosSite(6, 0, 487, 520, ppSlide)
        'AddPhosSite(6, 0, 507, 520, ppSlide)
        'AddPhosSite(6, 0, 512, 520, ppSlide)
        'AddPhosSite(6, 0, 513, 520, ppSlide)
        'AddPhosSite(6, 0, 461, 520, ppSlide)
        'AddPhosSite(6, 0, 510, 520, ppSlide)
        'AddMethSite(6, 0, 206, 520, ppSlide)
        'AddMethSite(6, 0, 504, 520, ppSlide)
        'AddPalmSite(6, 0, 226, 520, ppSlide)
        'AddPalmSite(6, 0, 514, 520, ppSlide)



        ''NTHL1
        'Dim protNum As Integer = 7
        'NewProtein(protNum, "NTHL1", 312, ppSlide)
        'AddMTS(protNum, 0, 1, 35, 312, ppSlide)
        'AddNLS(protNum, 0, 36, 44, 312, ppSlide)
        'AddNLS(protNum, 0, 54, 60, 312, ppSlide)
        'AddNLS(protNum, 0, 124, 131, 312, ppSlide)
        'AddNES(protNum, 0, 151, 161, 312, ppSlide)
        'AddMotif1(protNum, 0, 202, 231, 312, ppSlide)
        'AddSUMOSite(protNum, 0, 56, 312, ppSlide)
        'AddUbSite(protNum, 0, 75, 312, ppSlide)
        'AddAceSite(protNum, 0, 75, 312, ppSlide)
        'AddAceSite(protNum, 0, 190, 312, ppSlide)
        'AddAceSite(protNum, 0, 254, 312, ppSlide)
        'AddAceSite(protNum, 0, 257, 312, ppSlide)
        'AddMethSite(protNum, 0, 30, 312, ppSlide)
        'AddMethSite(protNum, 0, 157, 312, ppSlide)
        'AddPhosSite(protNum, 0, 13, 312, ppSlide)
        'AddPhosSite(protNum, 0, 22, 312, ppSlide)
        'AddPhosSite(protNum, 0, 51, 312, ppSlide)
        'AddPhosSite(protNum, 0, 53, 312, ppSlide)
        'AddPhosSite(protNum, 0, 73, 312, ppSlide)
        'AddPhosSite(protNum, 0, 207, 312, ppSlide)
        'AddPhosSite(protNum, 0, 258, 312, ppSlide)
        'AddPhosSite(protNum, 0, 252, 312, ppSlide)
        'AddPhosSite(protNum, 0, 119, 312, ppSlide)
        'AddPhosSite(protNum, 0, 188, 312, ppSlide)
        'AddPalmSite(protNum, 0, 2, 312, ppSlide)

        ''UNG1
        'protNum += 1
        'NewProtein(protNum, "UNG1", 304, ppSlide)
        'AddMotif1(protNum, 0, 138, 147, 304, ppSlide)
        'AddMTS(protNum, 0, 1, 29, 304, ppSlide)
        'AddNLS(protNum, 0, 267, 270, 304, ppSlide)
        'AddNES(protNum, 0, 22, 37, 304, ppSlide)
        'AddNES(protNum, 0, 201, 209, 304, ppSlide)
        'AddUbSite(protNum, 0, 40, 304, ppSlide)
        'AddUbSite(protNum, 0, 41, 304, ppSlide)
        'AddAceSite(protNum, 0, 20, 304, ppSlide)
        'AddAceSite(protNum, 0, 41, 304, ppSlide)
        'AddAceSite(protNum, 0, 99, 304, ppSlide)
        'AddAceSite(protNum, 0, 104, 304, ppSlide)
        'AddAceSite(protNum, 0, 251, 304, ppSlide)
        'AddAceSite(protNum, 0, 252, 304, ppSlide)
        'AddAceSite(protNum, 0, 259, 304, ppSlide)
        'AddAceSite(protNum, 0, 286, 304, ppSlide)
        'AddAceSite(protNum, 0, 293, 304, ppSlide)
        'AddMethSite(protNum, 0, 220, 304, ppSlide)
        'AddPhosSite(protNum, 0, 55, 304, ppSlide)
        'AddPhosSite(protNum, 0, 58, 304, ppSlide)
        'AddPhosSite(protNum, 0, 88, 304, ppSlide)
        'AddPhosSite(protNum, 0, 94, 304, ppSlide)
        'AddPhosSite(protNum, 0, 169, 304, ppSlide)
        'AddPhosSite(protNum, 0, 178, 304, ppSlide)
        'AddPhosSite(protNum, 0, 216, 304, ppSlide)
        'AddPhosSite(protNum, 0, 254, 304, ppSlide)
        'AddPhosSite(protNum, 0, 273, 304, ppSlide)
        'AddPhosSite(protNum, 0, 285, 304, ppSlide)
        'AddPhosSite(protNum, 0, 294, 304, ppSlide)
        'AddPhosSite(protNum, 0, 51, 304, ppSlide)
        'AddPhosSite(protNum, 0, 117, 304, ppSlide)
        'AddPalmSite(protNum, 0, 5, 304, ppSlide)
        'AddPalmSite(protNum, 0, 281, 304, ppSlide)

        ''UNG2
        'protNum += 1
        'NewProtein(protNum, "UNG2", 313, ppSlide)
        'AddMotif1(protNum, 0, 147, 156, 313, ppSlide)
        'AddMTS(protNum, 0, 1, 20, 313, ppSlide)
        'AddNLS(protNum, 0, 13, 21, 304, ppSlide)
        'AddNLS(protNum, 0, 276, 279, 313, ppSlide)
        'AddNES(protNum, 0, 210, 218, 313, ppSlide)
        'AddUbSite(protNum, 0, 49, 313, ppSlide)
        'AddUbSite(protNum, 0, 50, 313, ppSlide)
        'AddAceSite(protNum, 0, 49, 313, ppSlide)
        'AddAceSite(protNum, 0, 108, 313, ppSlide)
        'AddAceSite(protNum, 0, 113, 313, ppSlide)
        'AddAceSite(protNum, 0, 260, 313, ppSlide)
        'AddAceSite(protNum, 0, 261, 313, ppSlide)
        'AddAceSite(protNum, 0, 268, 313, ppSlide)
        'AddAceSite(protNum, 0, 295, 313, ppSlide)
        'AddAceSite(protNum, 0, 302, 313, ppSlide)
        'AddMethSite(protNum, 0, 229, 313, ppSlide)
        'AddPhosSite(protNum, 0, 12, 313, ppSlide)
        'AddPhosSite(protNum, 0, 14, 313, ppSlide)
        'AddPhosSite(protNum, 0, 23, 313, ppSlide)
        'AddPhosSite(protNum, 0, 40, 313, ppSlide)
        'AddPhosSite(protNum, 0, 64, 313, ppSlide)
        'AddPhosSite(protNum, 0, 67, 313, ppSlide)
        'AddPhosSite(protNum, 0, 97, 313, ppSlide)
        'AddPhosSite(protNum, 0, 103, 313, ppSlide)
        'AddPhosSite(protNum, 0, 178, 313, ppSlide)
        'AddPhosSite(protNum, 0, 187, 313, ppSlide)
        'AddPhosSite(protNum, 0, 225, 313, ppSlide)
        'AddPhosSite(protNum, 0, 263, 313, ppSlide)
        'AddPhosSite(protNum, 0, 282, 313, ppSlide)
        'AddPhosSite(protNum, 0, 294, 313, ppSlide)
        'AddPhosSite(protNum, 0, 60, 313, ppSlide)
        'AddPhosSite(protNum, 0, 126, 313, ppSlide)
        'AddPalmSite(protNum, 0, 290, 313, ppSlide)

        ''MPGa
        'Dim protLength As Integer = 298
        'protNum += 1
        'NewProtein(protNum, "MPGa", protLength, ppSlide)
        'AddMTS(protNum, 0, 1, 28, protLength, ppSlide)
        'AddNLS(protNum, 0, 13, 29, protLength, ppSlide)
        'AddNES(protNum, 0, 180, 200, protLength, ppSlide)
        'AddAceSite(protNum, 0, 22, protLength, ppSlide)
        'AddAceSite(protNum, 0, 202, protLength, ppSlide)
        'AddAceSite(protNum, 0, 229, protLength, ppSlide)
        'AddMethSite(protNum, 0, 138, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 33, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 48, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 78, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 137, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 172, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 282, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 286, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 67, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 143, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 199, protLength, ppSlide)
        'AddPalmSite(protNum, 0, 15, protLength, ppSlide)

        ''MPGb
        'protLength = 293
        'protNum += 1
        'NewProtein(protNum, "MPGb", protLength, ppSlide)
        'AddMTS(protNum, 0, 1, 23, protLength, ppSlide)
        'AddNES(protNum, 0, 175, 195, protLength, ppSlide)
        'AddAceSite(protNum, 0, 17, protLength, ppSlide)
        'AddAceSite(protNum, 0, 197, protLength, ppSlide)
        'AddAceSite(protNum, 0, 224, protLength, ppSlide)
        'AddMethSite(protNum, 0, 133, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 28, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 42, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 73, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 132, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 167, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 277, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 281, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 62, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 138, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 194, protLength, ppSlide)
        'AddPalmSite(protNum, 0, 10, protLength, ppSlide)

        ''MPGc
        'protLength = 281
        'protNum += 1
        'NewProtein(protNum, "MPGc", protLength, ppSlide)
        'AddMTS(protNum, 0, 1, 11, protLength, ppSlide)
        'AddNES(protNum, 0, 163, 183, protLength, ppSlide)
        'AddAceSite(protNum, 0, 185, protLength, ppSlide)
        'AddAceSite(protNum, 0, 212, protLength, ppSlide)
        'AddMethSite(protNum, 0, 121, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 16, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 30, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 61, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 120, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 155, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 265, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 269, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 50, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 126, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 182, protLength, ppSlide)

        ''OGG1-1a
        'protLength = 345
        'protNum += 1
        'NewProtein(protNum, "OGG1-1a", protLength, ppSlide)
        'AddMTS(protNum, 0, 1, 31, protLength, ppSlide)
        'AddNLS(protNum, 0, 332, 338, protLength, ppSlide)
        'AddNES(protNum, 0, 26, 39, protLength, ppSlide)
        'AddUbSite(protNum, 0, 82, protLength, ppSlide)
        'AddUbSite(protNum, 0, 289, protLength, ppSlide)
        'AddAceSite(protNum, 0, 335, protLength, ppSlide)
        'AddAceSite(protNum, 0, 338, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 16, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 31, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 51, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 86, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 209, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 211, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 231, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 232, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 280, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 326, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 67, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 89, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 156, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 248, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 295, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 233, protLength, ppSlide)

        ''OGG1-1b
        'protLength = 324
        'protNum += 1
        'NewProtein(protNum, "OGG1-1b", protLength, ppSlide)
        'AddMTS(protNum, 0, 1, 31, protLength, ppSlide)
        'AddNES(protNum, 0, 26, 39, protLength, ppSlide)
        'AddUbSite(protNum, 0, 82, protLength, ppSlide)
        'AddUbSite(protNum, 0, 289, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 16, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 31, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 51, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 86, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 209, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 211, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 231, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 232, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 280, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 67, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 89, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 156, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 248, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 295, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 233, protLength, ppSlide)

        ''OGG1-1c
        'protLength = 410
        'protNum += 1
        'NewProtein(protNum, "OGG1-1c", protLength, ppSlide)
        'AddMTS(protNum, 0, 1, 31, protLength, ppSlide)
        'AddNLS(protNum, 0, 346, 352, protLength, ppSlide)
        'AddNES(protNum, 0, 26, 39, protLength, ppSlide)
        'AddUbSite(protNum, 0, 82, protLength, ppSlide)
        'AddUbSite(protNum, 0, 289, protLength, ppSlide)
        'AddUbSite(protNum, 0, 358, protLength, ppSlide)
        'AddAceSite(protNum, 0, 347, protLength, ppSlide)
        'AddAceSite(protNum, 0, 391, protLength, ppSlide)
        'AddAceSite(protNum, 0, 398, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 16, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 31, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 51, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 86, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 209, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 211, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 231, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 232, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 280, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 341, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 365, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 371, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 373, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 375, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 378, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 400, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 67, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 89, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 156, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 248, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 295, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 355, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 389, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 233, protLength, ppSlide)
        'AddPalmSite(protNum, 0, 323, protLength, ppSlide)

        ''OGG1-2a
        'protLength = 424
        'protNum += 1
        'NewProtein(protNum, "OGG1-2a", protLength, ppSlide)
        'AddMTS(protNum, 0, 1, 31, protLength, ppSlide)
        'AddNES(protNum, 0, 26, 39, protLength, ppSlide)
        'AddUbSite(protNum, 0, 82, protLength, ppSlide)
        'AddUbSite(protNum, 0, 289, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 16, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 31, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 51, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 86, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 209, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 211, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 231, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 232, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 280, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 350, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 362, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 407, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 67, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 89, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 156, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 248, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 233, protLength, ppSlide)

        ''OGG1-2b
        'protLength = 357
        'protNum += 1
        'NewProtein(protNum, "OGG1-2b", protLength, ppSlide)
        'AddMTS(protNum, 0, 1, 31, protLength, ppSlide)
        'AddNES(protNum, 0, 26, 39, protLength, ppSlide)
        'AddUbSite(protNum, 0, 82, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 16, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 31, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 51, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 86, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 209, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 211, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 231, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 232, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 283, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 340, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 67, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 89, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 156, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 248, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 233, protLength, ppSlide)

        ''OGG1-2c
        'protLength = 195
        'protNum += 1
        'NewProtein(protNum, "OGG1-2c", protLength, ppSlide)
        'AddMTS(protNum, 0, 1, 31, protLength, ppSlide)
        'AddNES(protNum, 0, 26, 39, protLength, ppSlide)
        'AddUbSite(protNum, 0, 82, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 16, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 31, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 51, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 86, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 67, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 89, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 156, protLength, ppSlide)

        ''OGG1-2d
        'protLength = 356
        'protNum += 1
        'NewProtein(protNum, "OGG1-2d", protLength, ppSlide)
        'AddMTS(protNum, 0, 1, 31, protLength, ppSlide)
        'AddNES(protNum, 0, 26, 39, protLength, ppSlide)
        'AddUbSite(protNum, 0, 82, protLength, ppSlide)
        'AddUbSite(protNum, 0, 289, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 16, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 31, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 51, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 86, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 209, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 211, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 231, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 232, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 280, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 344, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 67, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 89, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 156, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 248, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 295, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 233, protLength, ppSlide)

        ''OGG1-2e
        'protLength = 322
        'protNum += 1
        'NewProtein(protNum, "OGG1-2e", protLength, ppSlide)
        'AddMTS(protNum, 0, 1, 31, protLength, ppSlide)
        'AddNES(protNum, 0, 26, 39, protLength, ppSlide)
        'AddUbSite(protNum, 0, 82, protLength, ppSlide)
        'AddUbSite(protNum, 0, 289, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 16, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 31, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 51, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 86, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 209, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 211, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 231, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 232, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 280, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 67, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 89, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 156, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 248, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 295, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 233, protLength, ppSlide)

        ''NEIL1-1
        'protLength = 476
        'protNum += 1
        'NewProtein(protNum, "NEIL1-1", protLength, ppSlide)
        'AddMotif1(protNum, 0, 88, 207, protLength, ppSlide)
        'AddMTS(protNum, 0, 1, 88, protLength, ppSlide)
        'AddNLS(protNum, 0, 376, 385, protLength, ppSlide)
        'AddNLS(protNum, 0, 407, 413, protLength, ppSlide)
        'AddNLS(protNum, 0, 445, 464, protLength, ppSlide)
        'AddNES(protNum, 0, 53, 61, protLength, ppSlide)
        'AddSUMOSite(protNum, 0, 462, protLength, ppSlide)
        'AddUbSite(protNum, 0, 462, protLength, ppSlide)
        'AddAceSite(protNum, 0, 13, protLength, ppSlide)
        'AddAceSite(protNum, 0, 24, protLength, ppSlide)
        'AddAceSite(protNum, 0, 42, protLength, ppSlide)
        'AddAceSite(protNum, 0, 50, protLength, ppSlide)
        'AddAceSite(protNum, 0, 241, protLength, ppSlide)
        'AddAceSite(protNum, 0, 279, protLength, ppSlide)
        'AddAceSite(protNum, 0, 301, protLength, ppSlide)
        'AddAceSite(protNum, 0, 305, protLength, ppSlide)
        'AddAceSite(protNum, 0, 320, protLength, ppSlide)
        'AddAceSite(protNum, 0, 377, protLength, ppSlide)
        'AddAceSite(protNum, 0, 380, protLength, ppSlide)
        'AddAceSite(protNum, 0, 419, protLength, ppSlide)
        'AddAceSite(protNum, 0, 460, protLength, ppSlide)
        'AddAceSite(protNum, 0, 462, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 18, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 22, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 26, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 46, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 84, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 117, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 119, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 136, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 282, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 293, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 332, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 334, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 381, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 386, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 392, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 408, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 80, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 423, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 131, protLength, ppSlide)

        ''NEIL1-2
        'protLength = 390
        'protNum += 1
        'NewProtein(protNum, "NEIL1-2", protLength, ppSlide)
        'AddMotif1(protNum, 0, 2, 121, protLength, ppSlide)
        'AddNLS(protNum, 0, 290, 299, protLength, ppSlide)
        'AddNLS(protNum, 0, 321, 327, protLength, ppSlide)
        'AddNLS(protNum, 0, 359, 378, protLength, ppSlide)
        'AddNES(protNum, 0, 110, 117, protLength, ppSlide)
        'AddNES(protNum, 0, 178, 188, protLength, ppSlide)
        'AddSUMOSite(protNum, 0, 376, protLength, ppSlide)
        'AddUbSite(protNum, 0, 376, protLength, ppSlide)
        'AddAceSite(protNum, 0, 155, protLength, ppSlide)
        'AddAceSite(protNum, 0, 193, protLength, ppSlide)
        'AddAceSite(protNum, 0, 215, protLength, ppSlide)
        'AddAceSite(protNum, 0, 219, protLength, ppSlide)
        'AddAceSite(protNum, 0, 234, protLength, ppSlide)
        'AddAceSite(protNum, 0, 291, protLength, ppSlide)
        'AddAceSite(protNum, 0, 294, protLength, ppSlide)
        'AddAceSite(protNum, 0, 333, protLength, ppSlide)
        'AddAceSite(protNum, 0, 374, protLength, ppSlide)
        'AddAceSite(protNum, 0, 376, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 31, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 33, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 50, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 196, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 207, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 246, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 248, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 295, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 300, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 306, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 322, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 337, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 45, protLength, ppSlide)

        ''NEIL2a
        'protLength = 332
        'protNum += 1
        'NewProtein(protNum, "NEIL2a", protLength, ppSlide)
        'AddMotif1(protNum, 0, 2, 156, protLength, ppSlide)
        'AddMotif1(protNum, 0, 284, 320, protLength, ppSlide)
        'AddMTS(protNum, 0, 1, 56, protLength, ppSlide)
        'AddNES(protNum, 0, 52, 62, protLength, ppSlide)
        'AddSUMOSite(protNum, 0, 234, protLength, ppSlide)
        'AddUbSite(protNum, 0, 80, protLength, ppSlide)
        'AddUbSite(protNum, 0, 87, protLength, ppSlide)
        'AddUbSite(protNum, 0, 96, protLength, ppSlide)
        'AddAceSite(protNum, 0, 9, protLength, ppSlide)
        'AddAceSite(protNum, 0, 24, protLength, ppSlide)
        'AddAceSite(protNum, 0, 30, protLength, ppSlide)
        'AddAceSite(protNum, 0, 31, protLength, ppSlide)
        'AddAceSite(protNum, 0, 50, protLength, ppSlide)
        'AddAceSite(protNum, 0, 96, protLength, ppSlide)
        'AddAceSite(protNum, 0, 154, protLength, ppSlide)
        'AddAceSite(protNum, 0, 200, protLength, ppSlide)
        'AddAceSite(protNum, 0, 288, protLength, ppSlide)
        'AddAceSite(protNum, 0, 299, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 29, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 68, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 101, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 102, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 104, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 162, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 183, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 187, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 198, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 227, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 255, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 323, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 70, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 117, protLength, ppSlide)

        ''NEIL2b
        'protLength = 271
        'protNum += 1
        'NewProtein(protNum, "NEIL2b", protLength, ppSlide)
        'AddMotif1(protNum, 0, 223, 259, protLength, ppSlide)
        'AddNES(protNum, 0, 185, 191, protLength, ppSlide)
        'AddSUMOSite(protNum, 0, 173, protLength, ppSlide)
        'AddUbSite(protNum, 0, 19, protLength, ppSlide)
        'AddUbSite(protNum, 0, 26, protLength, ppSlide)
        'AddUbSite(protNum, 0, 35, protLength, ppSlide)
        'AddAceSite(protNum, 0, 35, protLength, ppSlide)
        'AddAceSite(protNum, 0, 93, protLength, ppSlide)
        'AddAceSite(protNum, 0, 139, protLength, ppSlide)
        'AddAceSite(protNum, 0, 227, protLength, ppSlide)
        'AddAceSite(protNum, 0, 238, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 7, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 40, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 41, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 43, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 101, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 122, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 126, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 137, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 166, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 194, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 262, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 9, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 56, protLength, ppSlide)

        ''NEIL2c
        'protLength = 216
        'protNum += 1
        'NewProtein(protNum, "NEIL2c", protLength, ppSlide)
        'AddMotif1(protNum, 0, 168, 204, protLength, ppSlide)
        'AddMTS(protNum, 0, 1, 49, protLength, ppSlide)
        'AddNES(protNum, 0, 32, 51, protLength, ppSlide)
        'AddSUMOSite(protNum, 0, 183, protLength, ppSlide)
        'AddUbSite(protNum, 0, 80, protLength, ppSlide)
        'AddUbSite(protNum, 0, 87, protLength, ppSlide)
        'AddUbSite(protNum, 0, 96, protLength, ppSlide)
        'AddAceSite(protNum, 0, 9, protLength, ppSlide)
        'AddAceSite(protNum, 0, 24, protLength, ppSlide)
        'AddAceSite(protNum, 0, 30, protLength, ppSlide)
        'AddAceSite(protNum, 0, 31, protLength, ppSlide)
        'AddAceSite(protNum, 0, 84, protLength, ppSlide)
        'AddAceSite(protNum, 0, 172, protLength, ppSlide)
        'AddAceSite(protNum, 0, 183, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 29, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 67, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 71, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 82, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 111, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 139, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 207, protLength, ppSlide)

        ''NEIL3
        'protLength = 605
        'protNum += 1
        'NewProtein(protNum, "NEIL3", protLength, ppSlide)
        'AddMotif1(protNum, 0, 2, 137, protLength, ppSlide)
        'AddMotif1(protNum, 0, 247, 281, protLength, ppSlide)
        'AddMotif2(protNum, 0, 317, 346, protLength, ppSlide)
        'AddNLS(protNum, 0, 462, 468, protLength, ppSlide)
        'AddNES(protNum, 0, 32, 40, protLength, ppSlide)
        'AddSUMOSite(protNum, 0, 195, protLength, ppSlide)
        'AddSUMOSite(protNum, 0, 351, protLength, ppSlide)
        'AddUbSite(protNum, 0, 351, protLength, ppSlide)
        'AddUbSite(protNum, 0, 398, protLength, ppSlide)
        'AddUbSite(protNum, 0, 405, protLength, ppSlide)
        'AddUbSite(protNum, 0, 407, protLength, ppSlide)
        'AddUbSite(protNum, 0, 434, protLength, ppSlide)
        'AddUbSite(protNum, 0, 435, protLength, ppSlide)
        'AddUbSite(protNum, 0, 446, protLength, ppSlide)
        'AddUbSite(protNum, 0, 478, protLength, ppSlide)
        'AddAceSite(protNum, 0, 110, protLength, ppSlide)
        'AddAceSite(protNum, 0, 244, protLength, ppSlide)
        'AddAceSite(protNum, 0, 372, protLength, ppSlide)
        'AddAceSite(protNum, 0, 378, protLength, ppSlide)
        'AddAceSite(protNum, 0, 382, protLength, ppSlide)
        'AddAceSite(protNum, 0, 458, protLength, ppSlide)
        'AddAceSite(protNum, 0, 465, protLength, ppSlide)
        'AddAceSite(protNum, 0, 466, protLength, ppSlide)
        'AddAceSite(protNum, 0, 509, protLength, ppSlide)
        'AddAceSite(protNum, 0, 558, protLength, ppSlide)
        'AddAceSite(protNum, 0, 563, protLength, ppSlide)
        'AddAceSite(protNum, 0, 574, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 30, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 50, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 133, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 140, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 143, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 157, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 167, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 229, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 300, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 303, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 304, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 317, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 334, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 352, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 356, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 396, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 400, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 419, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 444, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 445, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 450, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 454, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 457, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 461, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 473, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 474, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 504, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 508, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 560, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 342, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 389, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 561, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 111, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 484, protLength, ppSlide)
        'AddPalmSite(protNum, 0, 7, protLength, ppSlide)
        'AddPalmSite(protNum, 0, 554, protLength, ppSlide)

        ''MYH-1
        'protLength = 546
        'protNum += 1
        'NewProtein(protNum, "MYH-1", protLength, ppSlide)
        'AddMotif1(protNum, 0, 364, 495, protLength, ppSlide)
        'AddMTS(protNum, 0, 1, 37, protLength, ppSlide)
        'AddNLS(protNum, 0, 16, 19, protLength, ppSlide)
        'AddNLS(protNum, 0, 109, 115, protLength, ppSlide)
        'AddNLS(protNum, 0, 513, 520, protLength, ppSlide)
        'AddNES(protNum, 0, 108, 120, protLength, ppSlide)
        'AddUbSite(protNum, 0, 47, protLength, ppSlide)
        'AddAceSite(protNum, 0, 28, protLength, ppSlide)
        'AddAceSite(protNum, 0, 38, protLength, ppSlide)
        'AddAceSite(protNum, 0, 41, protLength, ppSlide)
        'AddAceSite(protNum, 0, 47, protLength, ppSlide)
        'AddAceSite(protNum, 0, 358, protLength, ppSlide)
        'AddAceSite(protNum, 0, 488, protLength, ppSlide)
        'AddAceSite(protNum, 0, 506, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 9, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 32, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 49, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 99, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 163, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 321, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 323, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 360, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 505, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 508, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 511, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 512, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 515, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 532, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 540, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 474, protLength, ppSlide)

        ''MYH-2
        'protLength = 535
        'protNum += 1
        'NewProtein(protNum, "MYH-2", protLength, ppSlide)
        'AddMotif1(protNum, 0, 353, 484, protLength, ppSlide)
        'AddMTS(protNum, 0, 1, 37, protLength, ppSlide)
        'AddNLS(protNum, 0, 16, 19, protLength, ppSlide)
        'AddNLS(protNum, 0, 101, 107, protLength, ppSlide)
        'AddNLS(protNum, 0, 505, 512, protLength, ppSlide)
        'AddNES(protNum, 0, 97, 109, protLength, ppSlide)
        'AddAceSite(protNum, 0, 28, protLength, ppSlide)
        'AddAceSite(protNum, 0, 38, protLength, ppSlide)
        'AddAceSite(protNum, 0, 41, protLength, ppSlide)
        'AddAceSite(protNum, 0, 47, protLength, ppSlide)
        'AddAceSite(protNum, 0, 347, protLength, ppSlide)
        'AddAceSite(protNum, 0, 477, protLength, ppSlide)
        'AddAceSite(protNum, 0, 495, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 9, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 32, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 49, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 88, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 152, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 310, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 312, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 349, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 494, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 497, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 500, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 501, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 504, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 521, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 529, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 463, protLength, ppSlide)

        ''MYH-3
        'protLength = 522
        'protNum += 1
        'NewProtein(protNum, "MYH-3", protLength, ppSlide)
        'AddMotif1(protNum, 0, 340, 471, protLength, ppSlide)
        'AddNLS(protNum, 0, 2, 5, protLength, ppSlide)
        'AddNLS(protNum, 0, 85, 91, protLength, ppSlide)
        'AddNLS(protNum, 0, 489, 496, protLength, ppSlide)
        'AddNES(protNum, 0, 84, 96, protLength, ppSlide)
        'AddAceSite(protNum, 0, 14, protLength, ppSlide)
        'AddAceSite(protNum, 0, 24, protLength, ppSlide)
        'AddAceSite(protNum, 0, 27, protLength, ppSlide)
        'AddAceSite(protNum, 0, 33, protLength, ppSlide)
        'AddAceSite(protNum, 0, 334, protLength, ppSlide)
        'AddAceSite(protNum, 0, 464, protLength, ppSlide)
        'AddAceSite(protNum, 0, 482, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 18, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 35, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 75, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 139, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 297, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 299, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 336, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 481, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 484, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 487, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 488, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 491, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 508, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 516, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 450, protLength, ppSlide)

        ''MYH-4
        'protLength = 521
        'protNum += 1
        'NewProtein(protNum, "MYH-4", protLength, ppSlide)
        'AddMotif1(protNum, 0, 339, 470, protLength, ppSlide)
        'AddNLS(protNum, 0, 2, 5, protLength, ppSlide)
        'AddNLS(protNum, 0, 84, 90, protLength, ppSlide)
        'AddNLS(protNum, 0, 488, 495, protLength, ppSlide)
        'AddNES(protNum, 0, 84, 96, protLength, ppSlide)
        'AddAceSite(protNum, 0, 14, protLength, ppSlide)
        'AddAceSite(protNum, 0, 24, protLength, ppSlide)
        'AddAceSite(protNum, 0, 27, protLength, ppSlide)
        'AddAceSite(protNum, 0, 33, protLength, ppSlide)
        'AddAceSite(protNum, 0, 333, protLength, ppSlide)
        'AddAceSite(protNum, 0, 463, protLength, ppSlide)
        'AddAceSite(protNum, 0, 481, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 18, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 35, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 75, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 138, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 296, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 298, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 335, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 480, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 483, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 486, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 487, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 490, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 507, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 515, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 449, protLength, ppSlide)

        ''MYH-5
        'protLength = 549
        'protNum += 1
        'NewProtein(protNum, "MYH-5", protLength, ppSlide)
        'AddMotif1(protNum, 0, 367, 498, protLength, ppSlide)
        'AddMTS(protNum, 0, 1, 37, protLength, ppSlide)
        'AddNLS(protNum, 0, 16, 19, protLength, ppSlide)
        'AddNLS(protNum, 0, 112, 118, protLength, ppSlide)
        'AddNLS(protNum, 0, 516, 523, protLength, ppSlide)
        'AddNES(protNum, 0, 111, 123, protLength, ppSlide)
        'AddUbSite(protNum, 0, 47, protLength, ppSlide)
        'AddAceSite(protNum, 0, 28, protLength, ppSlide)
        'AddAceSite(protNum, 0, 38, protLength, ppSlide)
        'AddAceSite(protNum, 0, 41, protLength, ppSlide)
        'AddAceSite(protNum, 0, 47, protLength, ppSlide)
        'AddAceSite(protNum, 0, 361, protLength, ppSlide)
        'AddAceSite(protNum, 0, 491, protLength, ppSlide)
        'AddAceSite(protNum, 0, 509, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 9, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 32, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 49, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 102, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 166, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 324, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 326, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 363, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 508, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 511, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 514, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 515, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 518, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 535, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 543, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 477, protLength, ppSlide)

        ''SMUG1-1
        'protLength = 270
        'protNum += 1
        'NewProtein(protNum, "SMUG1-1", protLength, ppSlide)
        'AddNES(protNum, 0, 27, 45, protLength, ppSlide)
        'AddNES(protNum, 0, 254, 269, protLength, ppSlide)
        'AddUbSite(protNum, 0, 123, protLength, ppSlide)
        'AddAceSite(protNum, 0, 77, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 30, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 241, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 94, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 116, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 178, protLength, ppSlide)

        ''SMUG1-2
        'protLength = 177
        'protNum += 1
        'NewProtein(protNum, "SMUG1-2", protLength, ppSlide)
        'AddNES(protNum, 0, 27, 45, protLength, ppSlide)
        'AddUbSite(protNum, 0, 123, protLength, ppSlide)
        'AddSUMOSite(protNum, 0, 146, protLength, ppSlide)
        'AddAceSite(protNum, 0, 77, protLength, ppSlide)
        'AddAceSite(protNum, 0, 160, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 30, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 140, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 94, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 116, protLength, ppSlide)

        ''MBD4-1
        'protLength = 580
        'protNum += 1
        'NewProtein(protNum, "MBD4-1", protLength, ppSlide)
        'AddMotif2(protNum, 0, 76, 148, protLength, ppSlide)
        'AddNLS(protNum, 0, 229, 232, protLength, ppSlide)
        'AddNLS(protNum, 0, 242, 248, protLength, ppSlide)
        'AddNLS(protNum, 0, 430, 436, protLength, ppSlide)
        'AddNES(protNum, 0, 502, 511, protLength, ppSlide)
        'AddSUMOSite(protNum, 0, 137, protLength, ppSlide)
        'AddSUMOSite(protNum, 0, 215, protLength, ppSlide)
        'AddUbSite(protNum, 0, 36, protLength, ppSlide)
        'AddUbSite(protNum, 0, 56, protLength, ppSlide)
        'AddUbSite(protNum, 0, 130, protLength, ppSlide)
        'AddUbSite(protNum, 0, 215, protLength, ppSlide)
        'AddUbSite(protNum, 0, 263, protLength, ppSlide)
        'AddUbSite(protNum, 0, 270, protLength, ppSlide)
        'AddUbSite(protNum, 0, 271, protLength, ppSlide)
        'AddUbSite(protNum, 0, 328, protLength, ppSlide)
        'AddUbSite(protNum, 0, 335, protLength, ppSlide)
        'AddUbSite(protNum, 0, 340, protLength, ppSlide)
        'AddUbSite(protNum, 0, 347, protLength, ppSlide)
        'AddUbSite(protNum, 0, 377, protLength, ppSlide)
        'AddUbSite(protNum, 0, 391, protLength, ppSlide)
        'AddUbSite(protNum, 0, 397, protLength, ppSlide)
        'AddAceSite(protNum, 0, 101, protLength, ppSlide)
        'AddAceSite(protNum, 0, 117, protLength, ppSlide)
        'AddAceSite(protNum, 0, 148, protLength, ppSlide)
        'AddAceSite(protNum, 0, 152, protLength, ppSlide)
        'AddAceSite(protNum, 0, 156, protLength, ppSlide)
        'AddAceSite(protNum, 0, 244, protLength, ppSlide)
        'AddAceSite(protNum, 0, 245, protLength, ppSlide)
        'AddAceSite(protNum, 0, 247, protLength, ppSlide)
        'AddAceSite(protNum, 0, 248, protLength, ppSlide)
        'AddAceSite(protNum, 0, 263, protLength, ppSlide)
        'AddAceSite(protNum, 0, 270, protLength, ppSlide)
        'AddAceSite(protNum, 0, 311, protLength, ppSlide)
        'AddAceSite(protNum, 0, 340, protLength, ppSlide)
        'AddAceSite(protNum, 0, 421, protLength, ppSlide)
        'AddAceSite(protNum, 0, 436, protLength, ppSlide)
        'AddAceSite(protNum, 0, 472, protLength, ppSlide)
        'AddAceSite(protNum, 0, 480, protLength, ppSlide)
        'AddAceSite(protNum, 0, 518, protLength, ppSlide)
        'AddAceSite(protNum, 0, 562, protLength, ppSlide)
        'AddMethSite(protNum, 0, 14, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 8, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 10, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 22, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 58, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 59, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 85, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 122, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 135, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 147, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 153, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 182, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 194, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 195, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 205, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 253, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 262, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 266, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 282, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 304, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 308, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 316, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 318, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 319, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 330, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 338, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 342, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 355, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 380, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 387, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 415, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 419, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 428, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 443, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 470, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 487, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 520, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 544, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 21, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 80, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 351, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 360, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 515, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 348, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 523, protLength, ppSlide)

        ''MBD4-2
        'protLength = 574
        'protNum += 1
        'NewProtein(protNum, "MBD4-2", protLength, ppSlide)
        'AddMotif2(protNum, 0, 76, 148, protLength, ppSlide)
        'AddNLS(protNum, 0, 229, 232, protLength, ppSlide)
        'AddNLS(protNum, 0, 242, 248, protLength, ppSlide)
        'AddNLS(protNum, 0, 424, 430, protLength, ppSlide)
        'AddNES(protNum, 0, 496, 505, protLength, ppSlide)
        'AddSUMOSite(protNum, 0, 137, protLength, ppSlide)
        'AddSUMOSite(protNum, 0, 215, protLength, ppSlide)
        'AddUbSite(protNum, 0, 36, protLength, ppSlide)
        'AddUbSite(protNum, 0, 56, protLength, ppSlide)
        'AddUbSite(protNum, 0, 130, protLength, ppSlide)
        'AddUbSite(protNum, 0, 215, protLength, ppSlide)
        'AddUbSite(protNum, 0, 263, protLength, ppSlide)
        'AddUbSite(protNum, 0, 270, protLength, ppSlide)
        'AddUbSite(protNum, 0, 271, protLength, ppSlide)
        'AddUbSite(protNum, 0, 328, protLength, ppSlide)
        'AddUbSite(protNum, 0, 335, protLength, ppSlide)
        'AddUbSite(protNum, 0, 340, protLength, ppSlide)
        'AddUbSite(protNum, 0, 347, protLength, ppSlide)
        'AddUbSite(protNum, 0, 377, protLength, ppSlide)
        'AddUbSite(protNum, 0, 391, protLength, ppSlide)
        'AddUbSite(protNum, 0, 397, protLength, ppSlide)
        'AddAceSite(protNum, 0, 101, protLength, ppSlide)
        'AddAceSite(protNum, 0, 117, protLength, ppSlide)
        'AddAceSite(protNum, 0, 148, protLength, ppSlide)
        'AddAceSite(protNum, 0, 152, protLength, ppSlide)
        'AddAceSite(protNum, 0, 156, protLength, ppSlide)
        'AddAceSite(protNum, 0, 244, protLength, ppSlide)
        'AddAceSite(protNum, 0, 245, protLength, ppSlide)
        'AddAceSite(protNum, 0, 247, protLength, ppSlide)
        'AddAceSite(protNum, 0, 248, protLength, ppSlide)
        'AddAceSite(protNum, 0, 263, protLength, ppSlide)
        'AddAceSite(protNum, 0, 270, protLength, ppSlide)
        'AddAceSite(protNum, 0, 311, protLength, ppSlide)
        'AddAceSite(protNum, 0, 340, protLength, ppSlide)
        'AddAceSite(protNum, 0, 415, protLength, ppSlide)
        'AddAceSite(protNum, 0, 430, protLength, ppSlide)
        'AddAceSite(protNum, 0, 466, protLength, ppSlide)
        'AddAceSite(protNum, 0, 474, protLength, ppSlide)
        'AddAceSite(protNum, 0, 512, protLength, ppSlide)
        'AddAceSite(protNum, 0, 556, protLength, ppSlide)
        'AddMethSite(protNum, 0, 14, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 8, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 10, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 22, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 58, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 59, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 85, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 122, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 135, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 147, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 153, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 182, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 194, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 195, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 205, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 253, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 262, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 266, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 282, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 304, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 308, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 316, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 318, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 319, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 330, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 338, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 342, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 355, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 380, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 387, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 409, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 413, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 414, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 437, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 464, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 481, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 514, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 538, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 21, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 80, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 351, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 360, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 509, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 348, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 523, protLength, ppSlide)

        ''MBD4-3
        'protLength = 572
        'protNum += 1
        'NewProtein(protNum, "MBD4-3", protLength, ppSlide)
        'AddMotif2(protNum, 0, 76, 148, protLength, ppSlide)
        'AddNLS(protNum, 0, 229, 232, protLength, ppSlide)
        'AddNLS(protNum, 0, 242, 248, protLength, ppSlide)
        'AddNLS(protNum, 0, 430, 436, protLength, ppSlide)
        'AddNES(protNum, 0, 502, 511, protLength, ppSlide)
        'AddSUMOSite(protNum, 0, 137, protLength, ppSlide)
        'AddSUMOSite(protNum, 0, 215, protLength, ppSlide)
        'AddUbSite(protNum, 0, 36, protLength, ppSlide)
        'AddUbSite(protNum, 0, 56, protLength, ppSlide)
        'AddUbSite(protNum, 0, 130, protLength, ppSlide)
        'AddUbSite(protNum, 0, 215, protLength, ppSlide)
        'AddUbSite(protNum, 0, 263, protLength, ppSlide)
        'AddUbSite(protNum, 0, 270, protLength, ppSlide)
        'AddUbSite(protNum, 0, 271, protLength, ppSlide)
        'AddUbSite(protNum, 0, 328, protLength, ppSlide)
        'AddUbSite(protNum, 0, 335, protLength, ppSlide)
        'AddUbSite(protNum, 0, 340, protLength, ppSlide)
        'AddUbSite(protNum, 0, 347, protLength, ppSlide)
        'AddUbSite(protNum, 0, 377, protLength, ppSlide)
        'AddUbSite(protNum, 0, 391, protLength, ppSlide)
        'AddUbSite(protNum, 0, 397, protLength, ppSlide)
        'AddUbSite(protNum, 0, 572, protLength, ppSlide)
        'AddAceSite(protNum, 0, 101, protLength, ppSlide)
        'AddAceSite(protNum, 0, 117, protLength, ppSlide)
        'AddAceSite(protNum, 0, 148, protLength, ppSlide)
        'AddAceSite(protNum, 0, 152, protLength, ppSlide)
        'AddAceSite(protNum, 0, 156, protLength, ppSlide)
        'AddAceSite(protNum, 0, 244, protLength, ppSlide)
        'AddAceSite(protNum, 0, 245, protLength, ppSlide)
        'AddAceSite(protNum, 0, 247, protLength, ppSlide)
        'AddAceSite(protNum, 0, 248, protLength, ppSlide)
        'AddAceSite(protNum, 0, 263, protLength, ppSlide)
        'AddAceSite(protNum, 0, 270, protLength, ppSlide)
        'AddAceSite(protNum, 0, 311, protLength, ppSlide)
        'AddAceSite(protNum, 0, 340, protLength, ppSlide)
        'AddAceSite(protNum, 0, 421, protLength, ppSlide)
        'AddAceSite(protNum, 0, 436, protLength, ppSlide)
        'AddAceSite(protNum, 0, 472, protLength, ppSlide)
        'AddAceSite(protNum, 0, 480, protLength, ppSlide)
        'AddAceSite(protNum, 0, 518, protLength, ppSlide)
        'AddAceSite(protNum, 0, 562, protLength, ppSlide)
        'AddMethSite(protNum, 0, 14, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 8, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 10, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 22, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 58, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 59, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 85, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 122, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 135, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 147, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 153, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 182, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 194, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 195, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 205, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 253, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 262, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 266, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 282, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 304, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 308, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 316, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 318, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 319, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 330, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 338, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 342, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 355, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 380, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 387, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 415, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 419, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 428, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 443, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 470, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 487, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 520, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 544, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 21, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 80, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 351, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 360, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 515, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 348, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 523, protLength, ppSlide)

        ''MBD4-4
        'protLength = 540
        'protNum += 1
        'NewProtein(protNum, "MBD4-4", protLength, ppSlide)
        'AddMotif2(protNum, 0, 76, 148, protLength, ppSlide)
        'AddNLS(protNum, 0, 229, 232, protLength, ppSlide)
        'AddNLS(protNum, 0, 242, 248, protLength, ppSlide)
        'AddNLS(protNum, 0, 430, 436, protLength, ppSlide)
        'AddNES(protNum, 0, 502, 511, protLength, ppSlide)
        'AddSUMOSite(protNum, 0, 137, protLength, ppSlide)
        'AddSUMOSite(protNum, 0, 215, protLength, ppSlide)
        'AddUbSite(protNum, 0, 36, protLength, ppSlide)
        'AddUbSite(protNum, 0, 56, protLength, ppSlide)
        'AddUbSite(protNum, 0, 130, protLength, ppSlide)
        'AddUbSite(protNum, 0, 215, protLength, ppSlide)
        'AddUbSite(protNum, 0, 263, protLength, ppSlide)
        'AddUbSite(protNum, 0, 270, protLength, ppSlide)
        'AddUbSite(protNum, 0, 271, protLength, ppSlide)
        'AddUbSite(protNum, 0, 328, protLength, ppSlide)
        'AddUbSite(protNum, 0, 335, protLength, ppSlide)
        'AddUbSite(protNum, 0, 340, protLength, ppSlide)
        'AddUbSite(protNum, 0, 347, protLength, ppSlide)
        'AddUbSite(protNum, 0, 377, protLength, ppSlide)
        'AddUbSite(protNum, 0, 391, protLength, ppSlide)
        'AddUbSite(protNum, 0, 397, protLength, ppSlide)
        'AddAceSite(protNum, 0, 101, protLength, ppSlide)
        'AddAceSite(protNum, 0, 117, protLength, ppSlide)
        'AddAceSite(protNum, 0, 148, protLength, ppSlide)
        'AddAceSite(protNum, 0, 152, protLength, ppSlide)
        'AddAceSite(protNum, 0, 156, protLength, ppSlide)
        'AddAceSite(protNum, 0, 244, protLength, ppSlide)
        'AddAceSite(protNum, 0, 245, protLength, ppSlide)
        'AddAceSite(protNum, 0, 247, protLength, ppSlide)
        'AddAceSite(protNum, 0, 248, protLength, ppSlide)
        'AddAceSite(protNum, 0, 263, protLength, ppSlide)
        'AddAceSite(protNum, 0, 270, protLength, ppSlide)
        'AddAceSite(protNum, 0, 311, protLength, ppSlide)
        'AddAceSite(protNum, 0, 340, protLength, ppSlide)
        'AddAceSite(protNum, 0, 421, protLength, ppSlide)
        'AddAceSite(protNum, 0, 436, protLength, ppSlide)
        'AddAceSite(protNum, 0, 472, protLength, ppSlide)
        'AddAceSite(protNum, 0, 480, protLength, ppSlide)
        'AddAceSite(protNum, 0, 518, protLength, ppSlide)
        'AddMethSite(protNum, 0, 14, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 8, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 10, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 22, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 58, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 59, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 85, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 122, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 135, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 147, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 153, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 182, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 194, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 195, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 205, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 253, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 262, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 266, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 282, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 304, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 308, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 316, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 318, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 319, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 330, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 338, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 342, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 355, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 380, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 387, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 415, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 419, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 428, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 443, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 470, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 487, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 520, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 21, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 80, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 351, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 360, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 515, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 348, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 523, protLength, ppSlide)

        ''MBD4-5
        'protLength = 262
        'protNum += 1
        'NewProtein(protNum, "MBD4-5", protLength, ppSlide)
        'AddNLS(protNum, 0, 111, 118, protLength, ppSlide)
        'AddNES(protNum, 0, 184, 193, protLength, ppSlide)
        'AddUbSite(protNum, 0, 36, protLength, ppSlide)
        'AddUbSite(protNum, 0, 56, protLength, ppSlide)
        'AddAceSite(protNum, 0, 103, protLength, ppSlide)
        'AddAceSite(protNum, 0, 118, protLength, ppSlide)
        'AddAceSite(protNum, 0, 154, protLength, ppSlide)
        'AddAceSite(protNum, 0, 162, protLength, ppSlide)
        'AddAceSite(protNum, 0, 200, protLength, ppSlide)
        'AddAceSite(protNum, 0, 244, protLength, ppSlide)
        'AddMethSite(protNum, 0, 14, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 8, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 10, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 22, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 58, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 59, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 97, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 101, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 110, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 125, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 152, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 169, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 202, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 226, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 197, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 205, protLength, ppSlide)

        ''TDG
        'protLength = 410
        'protNum += 1
        'NewProtein(protNum, "TDG", protLength, ppSlide)
        'AddNLS(protNum, 0, 58, 64, protLength, ppSlide)
        'AddNES(protNum, 0, 124, 134, protLength, ppSlide)
        'AddSUMOSite(protNum, 0, 105, protLength, ppSlide)
        'AddUbSite(protNum, 0, 201, protLength, ppSlide)
        'AddAceSite(protNum, 0, 62, protLength, ppSlide)
        'AddAceSite(protNum, 0, 84, protLength, ppSlide)
        'AddAceSite(protNum, 0, 87, protLength, ppSlide)
        'AddAceSite(protNum, 0, 90, protLength, ppSlide)
        'AddAceSite(protNum, 0, 107, protLength, ppSlide)
        'AddAceSite(protNum, 0, 161, protLength, ppSlide)
        'AddAceSite(protNum, 0, 201, protLength, ppSlide)
        'AddAceSite(protNum, 0, 206, protLength, ppSlide)
        'AddAceSite(protNum, 0, 218, protLength, ppSlide)
        'AddAceSite(protNum, 0, 221, protLength, ppSlide)
        'AddAceSite(protNum, 0, 291, protLength, ppSlide)
        'AddAceSite(protNum, 0, 330, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 82, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 85, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 88, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 91, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 200, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 204, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 205, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 239, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 373, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 376, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 394, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 197, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 334, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 338, protLength, ppSlide)
        'AddPhosSite(protNum, 0, 346, protLength, ppSlide)

        'APEX1
        Dim protLength As Integer = 318
        Dim protNum As Integer = 1
        NewProtein(protNum, "APEX1", protLength, ppSlide)
        AddMotif1(protNum, 0, 89, 98, protLength, ppSlide)
        AddMotif1(protNum, 0, 251, 267, protLength, ppSlide)
        AddMotif1(protNum, 0, 277, 288, protLength, ppSlide)
        AddNLS(protNum, 0, 2, 8, protLength, ppSlide)
        AddNLS(protNum, 0, 21, 27, protLength, ppSlide)
        AddNES(protNum, 0, 291, 300, protLength, ppSlide)
        AddNES(protNum, 0, 312, 318, protLength, ppSlide)
        AddSUMOSite(protNum, 0, 85, protLength, ppSlide)
        AddUbSite(protNum, 0, 35, protLength, ppSlide)
        AddAceSite(protNum, 0, 31, protLength, ppSlide)
        AddAceSite(protNum, 0, 58, protLength, ppSlide)
        AddAceSite(protNum, 0, 79, protLength, ppSlide)
        AddAceSite(protNum, 0, 197, protLength, ppSlide)
        AddAceSite(protNum, 0, 203, protLength, ppSlide)
        AddPhosSite(protNum, 0, 26, protLength, ppSlide)
        AddPhosSite(protNum, 0, 54, protLength, ppSlide)
        AddPhosSite(protNum, 0, 56, protLength, ppSlide)
        AddPhosSite(protNum, 0, 123, protLength, ppSlide)
        AddPhosSite(protNum, 0, 201, protLength, ppSlide)
        AddPhosSite(protNum, 0, 298, protLength, ppSlide)
        AddPhosSite(protNum, 0, 233, protLength, ppSlide)
        AddPhosSite(protNum, 0, 45, protLength, ppSlide)
        AddPhosSite(protNum, 0, 128, protLength, ppSlide)
        AddPalmSite(protNum, 0, 296, protLength, ppSlide)

        'APEX2-1
        protLength = 518
        protNum += 1
        NewProtein(protNum, "APEX2-1", protLength, ppSlide)
        AddMotif1(protNum, 0, 2, 313, protLength, ppSlide)
        AddMTS(protNum, 0, 1, 35, protLength, ppSlide)
        AddNES(protNum, 0, 36, 46, protLength, ppSlide)
        AddSUMOSite(protNum, 0, 253, protLength, ppSlide)
        AddSUMOSite(protNum, 0, 446, protLength, ppSlide)
        AddSUMOSite(protNum, 0, 482, protLength, ppSlide)
        AddUbSite(protNum, 0, 425, protLength, ppSlide)
        AddUbSite(protNum, 0, 430, protLength, ppSlide)
        AddUbSite(protNum, 0, 449, protLength, ppSlide)
        AddAceSite(protNum, 0, 50, protLength, ppSlide)
        AddAceSite(protNum, 0, 171, protLength, ppSlide)
        AddAceSite(protNum, 0, 394, protLength, ppSlide)
        AddAceSite(protNum, 0, 430, protLength, ppSlide)
        AddAceSite(protNum, 0, 434, protLength, ppSlide)
        AddAceSite(protNum, 0, 437, protLength, ppSlide)
        AddAceSite(protNum, 0, 446, protLength, ppSlide)
        AddAceSite(protNum, 0, 449, protLength, ppSlide)
        AddAceSite(protNum, 0, 457, protLength, ppSlide)
        AddPhosSite(protNum, 0, 71, protLength, ppSlide)
        AddPhosSite(protNum, 0, 73, protLength, ppSlide)
        AddPhosSite(protNum, 0, 77, protLength, ppSlide)
        AddPhosSite(protNum, 0, 80, protLength, ppSlide)
        AddPhosSite(protNum, 0, 376, protLength, ppSlide)
        AddPhosSite(protNum, 0, 382, protLength, ppSlide)
        AddPhosSite(protNum, 0, 386, protLength, ppSlide)
        AddPhosSite(protNum, 0, 400, protLength, ppSlide)
        AddPhosSite(protNum, 0, 443, protLength, ppSlide)
        AddPhosSite(protNum, 0, 454, protLength, ppSlide)
        AddPhosSite(protNum, 0, 458, protLength, ppSlide)
        AddPhosSite(protNum, 0, 506, protLength, ppSlide)
        AddPhosSite(protNum, 0, 507, protLength, ppSlide)
        AddPhosSite(protNum, 0, 423, protLength, ppSlide)
        AddPhosSite(protNum, 0, 426, protLength, ppSlide)
        AddPhosSite(protNum, 0, 278, protLength, ppSlide)
        AddPalmSite(protNum, 0, 321, protLength, ppSlide)
        AddPalmSite(protNum, 0, 509, protLength, ppSlide)

        'APEX2-2
        protLength = 347
        protNum += 1
        NewProtein(protNum, "APEX2-2", protLength, ppSlide)
        AddMotif1(protNum, 0, 1, 142, protLength, ppSlide)
        AddNES(protNum, 0, 6, 15, protLength, ppSlide)
        AddSUMOSite(protNum, 0, 82, protLength, ppSlide)
        AddSUMOSite(protNum, 0, 275, protLength, ppSlide)
        AddSUMOSite(protNum, 0, 311, protLength, ppSlide)
        AddUbSite(protNum, 0, 254, protLength, ppSlide)
        AddUbSite(protNum, 0, 259, protLength, ppSlide)
        AddUbSite(protNum, 0, 278, protLength, ppSlide)
        AddAceSite(protNum, 0, 223, protLength, ppSlide)
        AddAceSite(protNum, 0, 259, protLength, ppSlide)
        AddAceSite(protNum, 0, 263, protLength, ppSlide)
        AddAceSite(protNum, 0, 266, protLength, ppSlide)
        AddAceSite(protNum, 0, 275, protLength, ppSlide)
        AddAceSite(protNum, 0, 278, protLength, ppSlide)
        AddAceSite(protNum, 0, 286, protLength, ppSlide)
        AddPhosSite(protNum, 0, 205, protLength, ppSlide)
        AddPhosSite(protNum, 0, 211, protLength, ppSlide)
        AddPhosSite(protNum, 0, 215, protLength, ppSlide)
        AddPhosSite(protNum, 0, 229, protLength, ppSlide)
        AddPhosSite(protNum, 0, 272, protLength, ppSlide)
        AddPhosSite(protNum, 0, 283, protLength, ppSlide)
        AddPhosSite(protNum, 0, 287, protLength, ppSlide)
        AddPhosSite(protNum, 0, 335, protLength, ppSlide)
        AddPhosSite(protNum, 0, 336, protLength, ppSlide)
        AddPhosSite(protNum, 0, 252, protLength, ppSlide)
        AddPhosSite(protNum, 0, 255, protLength, ppSlide)
        AddPhosSite(protNum, 0, 107, protLength, ppSlide)
        AddPalmSite(protNum, 0, 150, protLength, ppSlide)
        AddPalmSite(protNum, 0, 338, protLength, ppSlide)

        'Ruler
        NewProtein(protNum + 1, "50aa", 50, ppSlide)

        'Console.Read()

        'ppPres.Close()
        'ppApp.Quit()
    End Sub

    Sub NewProtein(ByVal Index As Integer, ByVal Name As String, ByVal ProteinLength As Integer, ByRef ppSlide As PowerPoint.Slide)
        Dim BackboneShape As PowerPoint.Shape = ppSlide.Shapes.AddShape(MsoAutoShapeType.msoShapeRectangle, BackboneLeft, BackboneTop + 50 * Index, BackboneWidth * ProteinLength / MaxProteinLength, BackboneHeight)
        BackboneShape.Fill.ForeColor.RGB = RGB(0, 0, 0)
        BackboneShape.Fill.TwoColorGradient(MsoGradientStyle.msoGradientHorizontal, 2)
        BackboneShape.Fill.GradientStops.Insert(RGB(25, 25, 25), 0.8)
        BackboneShape.Fill.GradientStops.Insert(RGB(25, 25, 25), 1)
        BackboneShape.Fill.GradientStops.Delete(2)
        BackboneShape.Line.Visible = MsoTriState.msoFalse
        BackboneShape.Shadow.Type = MsoShadowType.msoShadow22 'Diffuse shadow directly down

        Dim ProteinLabel As PowerPoint.Shape = ppSlide.Shapes.AddTextbox(MsoTextOrientation.msoTextOrientationHorizontal, 0, FeatureTop + 50 * Index, 100, BackboneHeight)
        ProteinLabel.TextEffect.Text = Name

    End Sub

    Sub AddMTS(ByVal Index As Integer, ByVal Transparency As Single, ByVal StartResidue As Integer, ByVal EndResidue As Integer, ByVal ProteinLength As Integer, ByRef ppSlide As PowerPoint.Slide)
        Dim FeatureLeft As Single = CSng(BackboneLeft + (StartResidue - 1) / ProteinLength * BackboneWidth * ProteinLength / MaxProteinLength)
        Dim FeatureWidth As Single = CSng((EndResidue - StartResidue + 1) / ProteinLength * BackboneWidth * ProteinLength / MaxProteinLength)

        Dim MTSShape As PowerPoint.Shape = ppSlide.Shapes.AddShape(MsoAutoShapeType.msoShapeRectangle, FeatureLeft, FeatureTop + 50 * Index, FeatureWidth, FeatureHeight)
        MTSShape.Fill.TwoColorGradient(MsoGradientStyle.msoGradientHorizontal, 2)
        MTSShape.Fill.GradientStops.Insert(RGB(152, 93, 44), 0, Transparency) 'COM objects use BGR, not RGB, so this is backwards
        MTSShape.Fill.GradientStops.Insert(RGB(199, 123, 60), 0.8, Transparency)
        MTSShape.Fill.GradientStops.Insert(RGB(199, 123, 60), 1, Transparency)
        MTSShape.Fill.GradientStops.Delete(1)
        MTSShape.Fill.GradientStops.Delete(1)
        MTSShape.Line.Visible = MsoTriState.msoFalse
        MTSShape.Shadow.Type = MsoShadowType.msoShadow22 'Diffuse shadow directly down
    End Sub

    Sub AddNLS(ByVal Index As Integer, ByVal Transparency As Single, ByVal StartResidue As Integer, ByVal EndResidue As Integer, ByVal ProteinLength As Integer, ByRef ppSlide As PowerPoint.Slide)
        Dim FeatureLeft As Single = CSng(BackboneLeft + (StartResidue - 1) / ProteinLength * BackboneWidth * ProteinLength / MaxProteinLength)
        Dim FeatureWidth As Single = CSng((EndResidue - StartResidue + 1) / ProteinLength * BackboneWidth * ProteinLength / MaxProteinLength)

        Dim NLSShape As PowerPoint.Shape = ppSlide.Shapes.AddShape(MsoAutoShapeType.msoShapeRectangle, FeatureLeft, FeatureTop + 50 * Index, FeatureWidth, FeatureHeight)
        NLSShape.Fill.TwoColorGradient(MsoGradientStyle.msoGradientHorizontal, 2)
        NLSShape.Fill.GradientStops.Insert(RGB(29, 108, 96), 0, Transparency) 'COM objects use BGR, not RGB, so this is backwards
        NLSShape.Fill.GradientStops.Insert(RGB(42, 143, 255), 0.8, Transparency)
        NLSShape.Fill.GradientStops.Insert(RGB(42, 143, 255), 1, Transparency)
        NLSShape.Fill.GradientStops.Delete(1)
        NLSShape.Fill.GradientStops.Delete(1)
        NLSShape.Line.Visible = MsoTriState.msoFalse
        NLSShape.Shadow.Type = MsoShadowType.msoShadow22 'Diffuse shadow directly down
    End Sub

    Sub AddMotif1(ByVal Index As Integer, ByVal Transparency As Single, ByVal StartResidue As Integer, ByVal EndResidue As Integer, ByVal ProteinLength As Integer, ByRef ppSlide As PowerPoint.Slide)
        Dim FeatureLeft As Single = CSng(BackboneLeft + (StartResidue - 1) / ProteinLength * BackboneWidth * ProteinLength / MaxProteinLength)
        Dim FeatureWidth As Single = CSng((EndResidue - StartResidue + 1) / ProteinLength * BackboneWidth * ProteinLength / MaxProteinLength)

        Dim NLSShape As PowerPoint.Shape = ppSlide.Shapes.AddShape(MsoAutoShapeType.msoShapeRectangle, FeatureLeft, FeatureTop + 50 * Index, FeatureWidth, FeatureHeight)
        NLSShape.Fill.TwoColorGradient(MsoGradientStyle.msoGradientHorizontal, 2)
        NLSShape.Fill.GradientStops.Insert(RGB(29, 203, 207), 0, Transparency) 'COM objects use BGR, not RGB, so this is backwards
        NLSShape.Fill.GradientStops.Insert(RGB(43, 255, 255), 0.8, Transparency)
        NLSShape.Fill.GradientStops.Insert(RGB(43, 255, 255), 1, Transparency)
        NLSShape.Fill.GradientStops.Delete(1)
        NLSShape.Fill.GradientStops.Delete(1)
        NLSShape.Line.Visible = MsoTriState.msoFalse
        NLSShape.Shadow.Type = MsoShadowType.msoShadow22 'Diffuse shadow directly down
    End Sub

    Sub AddMotif2(ByVal Index As Integer, ByVal Transparency As Single, ByVal StartResidue As Integer, ByVal EndResidue As Integer, ByVal ProteinLength As Integer, ByRef ppSlide As PowerPoint.Slide)
        Dim FeatureLeft As Single = CSng(BackboneLeft + (StartResidue - 1) / ProteinLength * BackboneWidth * ProteinLength / MaxProteinLength)
        Dim FeatureWidth As Single = CSng((EndResidue - StartResidue + 1) / ProteinLength * BackboneWidth * ProteinLength / MaxProteinLength)

        Dim NLSShape As PowerPoint.Shape = ppSlide.Shapes.AddShape(MsoAutoShapeType.msoShapeRectangle, FeatureLeft, FeatureTop + 50 * Index, FeatureWidth, FeatureHeight)
        NLSShape.Fill.TwoColorGradient(MsoGradientStyle.msoGradientHorizontal, 2)
        NLSShape.Fill.GradientStops.Insert(RGB(43, 255, 255), 0, Transparency) 'COM objects use BGR, not RGB, so this is backwards
        NLSShape.Fill.GradientStops.Insert(RGB(29, 203, 207), 0.8, Transparency)
        NLSShape.Fill.GradientStops.Insert(RGB(43, 255, 255), 1, Transparency)
        NLSShape.Fill.GradientStops.Delete(1)
        NLSShape.Fill.GradientStops.Delete(1)
        NLSShape.Line.Visible = MsoTriState.msoFalse
        NLSShape.Shadow.Type = MsoShadowType.msoShadow22 'Diffuse shadow directly down
    End Sub

    Sub AddFeS(ByVal Index As Integer, ByVal Transparency As Single, ByVal StartResidue As Integer, ByVal EndResidue As Integer, ByVal ProteinLength As Integer, ByRef ppSlide As PowerPoint.Slide)
        Dim FeatureLeft As Single = CSng(BackboneLeft + (StartResidue - 1) / ProteinLength * BackboneWidth * ProteinLength / MaxProteinLength)
        Dim FeatureWidth As Single = CSng((EndResidue - StartResidue + 1) / ProteinLength * BackboneWidth * ProteinLength / MaxProteinLength)

        Dim NLSShape As PowerPoint.Shape = ppSlide.Shapes.AddShape(MsoAutoShapeType.msoShapeRectangle, FeatureLeft, FeatureTop + 50 * Index, FeatureWidth, FeatureHeight)
        NLSShape.Fill.TwoColorGradient(MsoGradientStyle.msoGradientHorizontal, 2)
        NLSShape.Fill.GradientStops.Insert(RGB(204, 0, 0), 0, Transparency) 'COM objects use BGR, not RGB, so this is backwards
        NLSShape.Fill.GradientStops.Insert(RGB(204, 0, 0), 0.8, Transparency)
        NLSShape.Fill.GradientStops.Insert(RGB(204, 0, 0), 1, Transparency)
        NLSShape.Fill.GradientStops.Delete(1)
        NLSShape.Fill.GradientStops.Delete(1)
        NLSShape.Line.Visible = MsoTriState.msoFalse
        NLSShape.Shadow.Type = MsoShadowType.msoShadow22 'Diffuse shadow directly down
    End Sub

    Sub AddNES(ByVal Index As Integer, ByVal Transparency As Single, ByVal StartResidue As Integer, ByVal EndResidue As Integer, ByVal ProteinLength As Integer, ByRef ppSlide As PowerPoint.Slide)
        Dim FeatureLeft As Single = CSng(BackboneLeft + (StartResidue - 1) / ProteinLength * BackboneWidth * ProteinLength / MaxProteinLength)
        Dim FeatureWidth As Single = CSng((EndResidue - StartResidue + 1) / ProteinLength * BackboneWidth * ProteinLength / MaxProteinLength)

        Dim NLSShape As PowerPoint.Shape = ppSlide.Shapes.AddShape(MsoAutoShapeType.msoShapeRectangle, FeatureLeft, FeatureTop + 50 * Index, FeatureWidth, FeatureHeight)
        NLSShape.Fill.TwoColorGradient(MsoGradientStyle.msoGradientHorizontal, 2)
        NLSShape.Fill.GradientStops.Insert(RGB(53, 149, 118), 0, Transparency) 'COM objects use BGR, not RGB, so this is backwards
        NLSShape.Fill.GradientStops.Insert(RGB(72, 195, 155), 0.8, Transparency)
        NLSShape.Fill.GradientStops.Insert(RGB(72, 195, 155), 1, Transparency)
        NLSShape.Fill.GradientStops.Delete(1)
        NLSShape.Fill.GradientStops.Delete(1)
        NLSShape.Line.Visible = MsoTriState.msoFalse
        NLSShape.Shadow.Type = MsoShadowType.msoShadow22 'Diffuse shadow directly down
    End Sub

    Sub AddSUMOSite(ByVal Index As Integer, ByVal Transparency As Single, ByVal Residue As Integer, ByVal ProteinLength As Integer, ByRef ppSlide As PowerPoint.Slide)
        Dim FeatureLeft As Single = CSng(BackboneLeft + (Residue - 1) / ProteinLength * BackboneWidth * ProteinLength / MaxProteinLength)
        Dim FeatureWidth As Single = CSng(1 / ProteinLength * BackboneWidth * ProteinLength / MaxProteinLength)

        Dim SUMOSiteShape As PowerPoint.Shape = ppSlide.Shapes.AddShape(MsoAutoShapeType.msoShapeRectangle, FeatureLeft, FeatureTop + 50 * Index, FeatureWidth, FeatureHeight / 4)
        SUMOSiteShape.Fill.TwoColorGradient(MsoGradientStyle.msoGradientHorizontal, 2)
        SUMOSiteShape.Fill.GradientStops.Insert(RGB(53, 149, 118), 0, Transparency) 'COM objects use BGR, not RGB, so this is backwards
        SUMOSiteShape.Fill.GradientStops.Insert(RGB(156, 199, 156), 0.8, Transparency)
        SUMOSiteShape.Fill.GradientStops.Insert(RGB(156, 199, 156), 1, Transparency)
        SUMOSiteShape.Fill.GradientStops.Delete(1)
        SUMOSiteShape.Fill.GradientStops.Delete(1)
        SUMOSiteShape.Line.Visible = MsoTriState.msoFalse
        SUMOSiteShape.Shadow.Type = MsoShadowType.msoShadow22 'Diffuse shadow directly down
    End Sub

    Sub AddUbSite(ByVal Index As Integer, ByVal Transparency As Single, ByVal Residue As Integer, ByVal ProteinLength As Integer, ByRef ppSlide As PowerPoint.Slide)
        Dim FeatureLeft As Single = CSng(BackboneLeft + (Residue - 1) / ProteinLength * BackboneWidth * ProteinLength / MaxProteinLength)
        Dim FeatureWidth As Single = CSng(1 / ProteinLength * BackboneWidth * ProteinLength / MaxProteinLength)

        Dim UbSiteShape As PowerPoint.Shape = ppSlide.Shapes.AddShape(MsoAutoShapeType.msoShapeRectangle, FeatureLeft, FeatureTop + FeatureHeight / 4 + 50 * Index, FeatureWidth, FeatureHeight / 4)
        UbSiteShape.Fill.TwoColorGradient(MsoGradientStyle.msoGradientHorizontal, 2)
        UbSiteShape.Fill.GradientStops.Insert(RGB(42, 45, 157), 0, Transparency) 'COM objects use BGR, not RGB, so this is backwards
        UbSiteShape.Fill.GradientStops.Insert(RGB(58, 61, 203), 0.8, Transparency)
        UbSiteShape.Fill.GradientStops.Insert(RGB(58, 61, 203), 1, Transparency)
        UbSiteShape.Fill.GradientStops.Delete(1)
        UbSiteShape.Fill.GradientStops.Delete(1)
        UbSiteShape.Line.Visible = MsoTriState.msoFalse
        UbSiteShape.Shadow.Type = MsoShadowType.msoShadow22 'Diffuse shadow directly down
    End Sub

    Sub AddPhosSite(ByVal Index As Integer, ByVal Transparency As Single, ByVal Residue As Integer, ByVal ProteinLength As Integer, ByRef ppSlide As PowerPoint.Slide)
        Dim FeatureLeft As Single = CSng(BackboneLeft + (Residue - 1) / ProteinLength * BackboneWidth * ProteinLength / MaxProteinLength)
        Dim FeatureWidth As Single = CSng(1 / ProteinLength * BackboneWidth * ProteinLength / MaxProteinLength)

        Dim PhosSiteShape As PowerPoint.Shape = ppSlide.Shapes.AddShape(MsoAutoShapeType.msoShapeRectangle, FeatureLeft, FeatureTop + 50 * Index, FeatureWidth, FeatureHeight)
        PhosSiteShape.Fill.TwoColorGradient(MsoGradientStyle.msoGradientHorizontal, 2)
        PhosSiteShape.Fill.GradientStops.Insert(RGB(160, 135, 39), 0, Transparency) 'COM objects use BGR, not RGB, so this is backwards
        PhosSiteShape.Fill.GradientStops.Insert(RGB(210, 177, 54), 0.8, Transparency)
        PhosSiteShape.Fill.GradientStops.Insert(RGB(210, 177, 54), 1, Transparency)
        PhosSiteShape.Fill.GradientStops.Delete(1)
        PhosSiteShape.Fill.GradientStops.Delete(1)
        PhosSiteShape.Line.Visible = MsoTriState.msoFalse
        PhosSiteShape.Shadow.Type = MsoShadowType.msoShadow22 'Diffuse shadow directly down
    End Sub

    Sub AddMethSite(ByVal Index As Integer, ByVal Transparency As Single, ByVal Residue As Integer, ByVal ProteinLength As Integer, ByRef ppSlide As PowerPoint.Slide)
        Dim FeatureLeft As Single = CSng(BackboneLeft + (Residue - 1) / ProteinLength * BackboneWidth * ProteinLength / MaxProteinLength)
        Dim FeatureWidth As Single = CSng(1 / ProteinLength * BackboneWidth * ProteinLength / MaxProteinLength)

        Dim PhosSiteShape As PowerPoint.Shape = ppSlide.Shapes.AddShape(MsoAutoShapeType.msoShapeRectangle, FeatureLeft, FeatureTop + FeatureHeight / 2 + 50 * Index, FeatureWidth, FeatureHeight / 4)
        PhosSiteShape.Fill.TwoColorGradient(MsoGradientStyle.msoGradientHorizontal, 2)
        PhosSiteShape.Fill.GradientStops.Insert(RGB(126, 65, 93), 0, Transparency) 'COM objects use BGR, not RGB, so this is backwards
        PhosSiteShape.Fill.GradientStops.Insert(RGB(166, 88, 123), 0.8, Transparency)
        PhosSiteShape.Fill.GradientStops.Insert(RGB(166, 88, 123), 1, Transparency)
        PhosSiteShape.Fill.GradientStops.Delete(1)
        PhosSiteShape.Fill.GradientStops.Delete(1)
        PhosSiteShape.Line.Visible = MsoTriState.msoFalse
        PhosSiteShape.Shadow.Type = MsoShadowType.msoShadow22 'Diffuse shadow directly down
    End Sub

    Sub AddAceSite(ByVal Index As Integer, ByVal Transparency As Single, ByVal Residue As Integer, ByVal ProteinLength As Integer, ByRef ppSlide As PowerPoint.Slide)
        Dim FeatureLeft As Single = CSng(BackboneLeft + (Residue - 1) / ProteinLength * BackboneWidth * ProteinLength / MaxProteinLength)
        Dim FeatureWidth As Single = CSng(1 / ProteinLength * BackboneWidth * ProteinLength / MaxProteinLength)

        Dim PhosSiteShape As PowerPoint.Shape = ppSlide.Shapes.AddShape(MsoAutoShapeType.msoShapeRectangle, FeatureLeft, FeatureTop + FeatureHeight / 4 * 3 + 50 * Index, FeatureWidth, FeatureHeight / 4)
        PhosSiteShape.Fill.TwoColorGradient(MsoGradientStyle.msoGradientHorizontal, 2)
        PhosSiteShape.Fill.GradientStops.Insert(RGB(255, 0, 0), 0, Transparency) 'COM objects use BGR, not RGB, so this is backwards
        PhosSiteShape.Fill.GradientStops.Insert(RGB(255, 0, 0), 0.8, Transparency)
        PhosSiteShape.Fill.GradientStops.Insert(RGB(255, 0, 0), 1, Transparency)
        PhosSiteShape.Fill.GradientStops.Delete(1)
        PhosSiteShape.Fill.GradientStops.Delete(1)
        PhosSiteShape.Line.Visible = MsoTriState.msoFalse
        PhosSiteShape.Shadow.Type = MsoShadowType.msoShadow22 'Diffuse shadow directly down
    End Sub

    Sub AddPalmSite(ByVal Index As Integer, ByVal Transparency As Single, ByVal Residue As Integer, ByVal ProteinLength As Integer, ByRef ppSlide As PowerPoint.Slide)
        Dim FeatureLeft As Single = CSng(BackboneLeft + (Residue - 1) / ProteinLength * BackboneWidth * ProteinLength / MaxProteinLength)
        Dim FeatureWidth As Single = CSng(1 / ProteinLength * BackboneWidth * ProteinLength / MaxProteinLength)

        Dim PhosSiteShape As PowerPoint.Shape = ppSlide.Shapes.AddShape(MsoAutoShapeType.msoShapeRectangle, FeatureLeft, FeatureTop + 50 * Index, FeatureWidth, FeatureHeight)
        PhosSiteShape.Fill.TwoColorGradient(MsoGradientStyle.msoGradientHorizontal, 2)
        PhosSiteShape.Fill.GradientStops.Insert(RGB(29, 203, 207), 0, Transparency) 'COM objects use BGR, not RGB, so this is backwards
        PhosSiteShape.Fill.GradientStops.Insert(RGB(43, 255, 255), 0.8, Transparency)
        PhosSiteShape.Fill.GradientStops.Insert(RGB(43, 255, 255), 1, Transparency)
        PhosSiteShape.Fill.GradientStops.Delete(1)
        PhosSiteShape.Fill.GradientStops.Delete(1)
        PhosSiteShape.Line.Visible = MsoTriState.msoFalse
        PhosSiteShape.Shadow.Type = MsoShadowType.msoShadow22 'Diffuse shadow directly down
    End Sub

End Module
